### PR TITLE
Updated install data

### PR DESCRIPTION
**Pull request by jorgenskogas**

### CODE REVIEW

**Comment by modius** [comment]
Looks great!  But what updates are in there? ;)

**Comment by jorgenskogas** [comment]
The site tree was corrupt, giving a error when accessing the site for the first time and when viewing the site in /webtop. I repaired the site tree, and run a fix refObjects and exported the data. :)

**Comment by justincarter** [comment]
It sounds like maybe it was an install where ?updateall=[appkey] wasn't run by the installer. A default skeleton has no refObjects, so it always needs to be rebuilt when the app starts up for the first time... (i.e. you'll notice there is no DATA-refObjects.sql file). So I don't think this pull request would fix anything?

**Comment by jorgenskogas** [comment]
Yes, you are absolutely right Justin. The installation is not running updateall=[appkey]. The installer also corrupts the farcryConstructor.cfm. Look like the installer corrupts the farcryConnector.cfm when the DSN has one or more numbers in it. I used 60722_testtest as DNS.

**Comment by jorgenskogas** [comment]
screenshot 2014-08-21 10 58 59

**Pull request closed without merging**
